name: Arbitrator skip CI
run-name: Arbitrator skip CI triggered from @${{ github.actor }} of ${{ github.head_ref }}

on:
  merge_group:
  pull_request:
    paths-ignore:
      - 'arbitrator/**'
      - 'nitro-contracts/src/osp/**'
      - 'nitro-contracts/src/mock/**'
      - 'nitro-contracts/test/**'
      - 'nitro-contracts/hardhat.config.ts'
      - 'Makefile'

jobs:
  arbitrator:
    name: Run Arbitrator tests
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "doing nothing"
